name: Build & Deploy Strapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build and Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/strapi:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE=ghcr.io/${{ github.repository_owner }}/strapi:latest
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull $IMAGE
            docker stop strapi || true
            docker rm strapi || true
            docker run -d --name strapi -p 1337:1337 $IMAGE
